### ISSUE TITLE
Unhandled exception: [Enter a title]

### ISSUE THREAD

**Issue by musienco-dn** [remyroy/CDDA-Game-Launcher#271]
* Description: [Enter what you did and what happened]
* Version: 1.3.18
* OS: Windows-10-10.0.17763 (64-bit)
* Type: `<class 'TypeError'>`
* Value: '<' not supported between instances of 'NoneType' and 'str'
* Traceback:
```
  File "cddagl\ui.py", line 3169, in lb_http_finished

```

**Comment by egorzaderiy** [comment]
exact same happens for me

**Comment by egorzaderiy** [comment]
also even old launcher (1.3.15) fails with this error

**Comment by remyroy** [comment]
This seems related to how build filename where recently changed in the build server. @narc0tiq Can you clarify this? I can put a quick update to fix the regex that parse the filename.

**Comment by remyroy** [comment]
The regex fix is in 8a716547a4fbb2bf8df79af69c691bc1a1c7093d . I'll be doing a quick release for this.

**Comment by remyroy** [comment]
This should be fixed in 1.3.19 which was just released.

**Comment by remyroy** [comment]
So new filename seems to follow this structure now:

```cataclysmdda-0.D-Windows_x64-Tiles-8874.zip```

instead of the old:

```cataclysmdda-0.D-8873.zip```

in any case, the new regex will catch both of them in order to parse the build number.

**Comment by narc0tiq** [comment]
It's about to be worse than that: I have to remove the build hosting from my machine altogether, because out of the 4 TB of data transfer I have available per month, this month I've used... 4082 GB:
![image](https://user-images.githubusercontent.com/591573/56980615-789eb480-6b85-11e9-8f2f-f337a3c123f4.png)

Therefore, I can't keep hosting the files at all!

I've been working on making the Jenkins process automatically create Github releases for the experimentals -- testing is ongoing at https://github.com/narc0tiq/test-release-creation/releases, but expect a different repo to be hosting them (likely not the main repo, but another CleverRaven/something).

You might need to look into [PyGithub](https://pygithub.readthedocs.io/en/latest/index.html).

**Comment by remyroy** [comment]
That's unfortunate @narc0tiq . Let me know when you'll find an alternative hosting and when you will be switching so I can do a nice launcher release to avoid too much downtime for the users.

Github don't seem to have any bandwidth limit on release items as mention in their support section https://help.github.com/en/articles/distributing-large-binaries

**Comment by narc0tiq** [comment]
Yes, as I mentioned, this is why I'm currently working on getting Github releases created automatically by Jenkins. This is also why I had to change the filenames -- I needed to disambiguate the files from different platforms because they would stomp each other.

**Comment by narc0tiq** [comment]
Update provided in #277.
