### ISSUE TITLE
Crash after running in cmd

### ISSUE THREAD

**Issue by OtpalTS** [remyroy/CDDA-Game-Launcher#338]
* Description: I followed the instructions given in building.md, made sure everything was correctly installed and that I didn't forget anything (still quite possible) and after runing cddagl\launcher.py it opened the program for about 0.01 second and then threw this error. Should i include a log from cmd?(First time posting so sorry for anything wrong)
* Version: 1.3.22
* OS: Windows-7-6.1.7601-SP1 (64-bit)
* Type: `<class 'json.decoder.JSONDecodeError'>`
* Value: Expecting value: line 1 column 1 (char 0)
* Traceback:
```
  File "C:\Users\Otpal\Downloads\CDDA-Game-Launcher-1.3.22\cddagl\ui.py", line 3207, in lb_http_finished
    releases = json.loads(TextIOWrapper(self.lb_html, encoding='utf8'
  File "C:\Users\Otpal\AppData\Local\Programs\Python\Python37-32\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Otpal\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Otpal\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None

```

**Comment by remyroy** [comment]
With 096b3552979272edabce3c66889a81900331c630 , there should be a better way to handle this issue. If you want to update your repository with that change and test it again.

This might be triggered by the [rate limiting system](https://developer.github.com/v3/#rate-limiting) behind the Github API. By default, anonymous users (like the launcher) are provided with 60 requests per hours. Since we use 1 request to check for launcher update and 1 request each time we want to get the list of available builds, users might be hitting this limit. A simple solution for this is to wait a little for your limit to go back up to 60. A simple way to prevent this issue is to avoid restarting the launcher many times in a row and avoid spam clicking the refresh button (that refreshes the list of available builds).

**Comment by OtpalTS** [comment]
Worked like a charm, thank you.

**Comment by KurzedMetal** [comment]
A good idea would be catching that rate limit error from the headers, explain the situation to the user to wait a bit instead giving them an Exception error. That probably will prevent you having a bug once in a while about this.

@remyroy You can see how I did that error handling in one of my scripts in https://github.com/CleverRaven/Cataclysm-DDA/blob/master/tools/generate_changelog.py#L773

**Comment by remyroy** [comment]
@KurzedMetal All good :) I'm in the process of implementing something like that, yes.
