### ISSUE TITLE
@'s Soundpack: Add this new soundpack to the repository

### ISSUE THREAD

**Issue by Lamandus** [remyroy/CDDA-Game-Launcher#341]
* Name: @'s Soundpack
* Url: https://github.com/damalsk/damalsksoundpack/releases
* Author: damalsk
* Homepage: https://discourse.cataclysmdda.org/t/soundpack-s-soundpack-vehicle-sounds-licensed-music-and-more/20131
* Soundpack not found in version: 1.3.19

Not mine, but I would like to see it in the launcher as well. seems solid

**Comment by remyroy** [comment]
Thanks for the information. It will be added in the next version.

**Comment by damalsk** [comment]
Nice to see it's here already, I was going to make this request today since I released a **[new version](https://github.com/damalsk/damalsksoundpack/releases)** of this soundpack. 
Just wanna request a change for the url (https://github.com/damalsk/damalsksoundpack/releases) and the name is actually "@'s soundpack". 

Thanks for posting, and thanks to remyroy for taking a look at it.

**Comment by Lamandus** [comment]
No problem, damalsk, your soundpack is quite good actually. That's why I wanted to see it here.

**Comment by remyroy** [comment]
I'm gonna have to use the zip file from the release assets (located at https://github.com/damalsk/damalsksoundpack/archive/v0.2.zip ) since the library I use to decompress 7z archive cannot decompress the archive located at https://github.com/damalsk/damalsksoundpack/releases/download/v0.2/@.s.soundpack.7z .

If I may suggest, please do zip archives for your next releases @damalsk . It's easier for everyone involved even if the archive size is slightly bigger.

**Comment by remyroy** [comment]
Added with f7674cfc79e7ea195df46b89a15d71af4cb93507 . It will be part of the next release.

**Comment by damalsk** [comment]
Alright then, next versions will be on zip. The archive size doesn't change much anyway. 

The current version released has been changed to zip too just in case (https://github.com/damalsk/damalsksoundpack/releases).

Thanks again.
