### ISSUE TITLE
Launcher Not Downloading Latest Build

### ISSUE THREAD

**Issue by Randonx** [remyroy/CDDA-Game-Launcher#347]
Checked the launcher like I normally do when I get home from work.  Launcher -shows- 2 more versions past the one it would let me download.

I'm running Windows 10 Pro
Version 1.4 of the launcher
My game had previously been Build #9102
The furthest the launcher will let me update is to #9104,
despite showing further versions.

First time ever seeing this issue.

![Screenshot 2019-06-06 17 51 59](https://user-images.githubusercontent.com/50780860/59075382-153f2b00-8885-11e9-83e9-895d957630a5.png)

I hope this is enough information, if not let me know so I can update the post.

Thank you.

**Comment by remyroy** [comment]
The available builds are just that, builds that are available for download. They are the binaries available on https://github.com/CleverRaven/Cataclysm-DDA/releases . Now if you look at the last few releases, you will notice that they do not have Windows binaries in the assets list which means, at some point during the build process, the binaries were not uploaded on Github.

**Comment by remyroy** [comment]
@narc0tiq Is there an issue with the build server?

**Comment by remyroy** [comment]
It seems the build server is slowly adding those binaries. They might eventually be available.

**Comment by narc0tiq** [comment]
There's no issue I'm aware of, it's all up to GitHub from here.

**Comment by KurzedMetal** [comment]
The windows binaries were skipped for some reason:

Example https://ci.narc.ro/job/Cataclysm-Matrix/9106/
![image](https://user-images.githubusercontent.com/1426680/59120008-af0ce380-892a-11e9-9f37-95df16d6232e.png)

And not available in GitHub (binaries should be with the source too):
![image](https://user-images.githubusercontent.com/1426680/59120056-ccda4880-892a-11e9-9e2d-9a22fa8c3cec.png)

Doesn't seem like a Launcher bug, but it would be nice if it informs the user that they are not available.
I'd do it in the changelog if I had the info, but if you look in the first image they are reported as "success" and the API is not returning the "SKIPPED" detail.

**Comment by narc0tiq** [comment]
The matrix build 2106 failed:
![image](https://user-images.githubusercontent.com/591573/59124578-c074e080-8968-11e9-98d8-1aaa9d823257.png)


The tooltip in @KurzedMetal's post is showing that:
- "Success" is the last result for a Windows64+Tiles build, and
- "skipped" because the build was not attempted in matrix buid 2106.

Windows64+Tiles **was not built** in matrix build 2106 because the Linux64+Curses build failed:
![image](https://user-images.githubusercontent.com/591573/59124758-3416ed80-8969-11e9-8492-8ad4a20f45e2.png)
Linux64+Curses is the touchstone build, meaning that if it fails, none of the other matrix members are attempted, because it is assumed they will all fail. Otherwise, you have to wait for 90-ish minutes to find out the result of the matrix, which would almost certainly be all-red anyway.

The launcher should not show experimental releases that failed. The [official experimental releases page](https://cataclysmdda.org/experimental/) does not -- it checks whether any artifacts were generated, and failed builds do not generate artifacts.

**Comment by KurzedMetal** [comment]
Not showing the releases that failed or got skipped is not an option for the Launcher IMO.

The launcher gets the list of changes from Jenkins API, if we skip / hide those builds we would be hiding changelog info or attributing the changes to an incorrect builds.

IMO, this is easily fixable just making sure the users do know builds failed (and that have to wait for a new build in the future), instead of silently hiding issues, and I just make a PR to improve that.

Thanks for mentioning how Jenkins decide to skip builds, I didn't know or think of that. I actually thought that was manually requested by a dev (some command or action or something).

**Comment by Randonx** [comment]
I apologize for the post, all.  Didn't realize that was a thing.  It was strange to me that they would show up, but not be downloadable.  Thanks for all of the info.

**Comment by KurzedMetal** [comment]
No apologies is needed! :)
Your report was good, as you found something that didn't add up with the information the app provided.
