### ISSUE TITLE
Launcher missing files

### ISSUE THREAD

**Issue by Andrei831** [remyroy/CDDA-Game-Launcher#350]
after you update the game the launcher deletes itself
![Untitled](https://user-images.githubusercontent.com/51699029/59258479-bbea4980-8c40-11e9-96ec-8a9e0169bd5a.jpg)

**Comment by remyroy** [comment]
You should avoid installing the launcher in the game directory.

**Comment by KurzedMetal** [comment]
I've noticed a bunch of players doing this on the CDDA Discord.
They lost their saves, the installer lost its files...
Maybe we should add something to prevent users shooting their feet. 😞 

Also, I noticed recently the launcher has an option that "install CDDA inside the launcher folder". I think we may need to change that option now that the installer may be located inside Program Files and non-elevated users won't have access. I honestly never used that and I'm not sure the impact, but maybe it deserves a new bug to talk and assess that.

**Comment by narc0tiq** [comment]
The "_install CDDA inside the launcher folder_" option sounds useful for portable installs; I wouldn't want to lose the advantages of the launcher just because I want my Cata on a USB key. 

It seems to me that there are two variants:
- either detect whether the option should be enabled (e.g., by a `try`/`open('some-file.tmp', 'w')`, since that's easier than trying to parse ACLs), or
- have a config flag somewhere that marks the install as portable/non-portable.

Maybe even combine the two: on first launch, if config is unset, do detection and set it appropriately. Unset it when upgrading to allow re-detection.
