### ISSUE TITLE
[Portable] Launcher deletes itself when updating

### ISSUE THREAD

**Issue by stealthytanub** [remyroy/CDDA-Game-Launcher#368]
If you have the portable folder in the same folder as the main game, when you update it will move itself into the 'previous versions' folder and if you do it twice it sends itself to the recycling bin.

I've only updated to the new launcher recently and the old one didn't do this, so I'm not sure if it is intentional behaviour.
![image](https://i.imgur.com/xwygsje.png)

**Comment by KurzedMetal** [comment]
Yes, it's a known issue: don't put the Launcher INSIDE the game directory, you can do the other way around and place the Game inside the launcher Directory tho...

Basically, don't put `cddagl_portable` inside `Cataclysm - DDA` directory. Move `cddagl_portable` to download and then if you want move `Cataclysm - DDA` inside `cddagl_portable`.

This was already reported in #350 and it's in process of getting fixed in a PR I submitted yesterday in #367.

Anyways, thanks for the report, they are useful to improve the launcher :)

**Comment by KurzedMetal** [comment]
@remyroy This can be closed, shouldn't happen anymore
