### ISSUE TITLE
Unhandled exception: [Enter a title]

### ISSUE THREAD

**Issue by Daedracian** [remyroy/CDDA-Game-Launcher#370]
* Description: [Enter what you did and what happened]
* Version: 1.3.19
* OS: Windows-10-10.0.17763 (64-bit)
* Type: `<class 'FileNotFoundError'>`
* Value: [WinError 2] The system cannot find the file specified: 'C:\\Users\\jonny_000\\Desktop\\cdda\\newmod'
* Traceback:
```
  File "cddagl\ui.py", line 7078, in download_http_finished
  File "cddagl\ui.py", line 7167, in extract_new_mod
  File "os.py", line 220, in makedirs

```

**Comment by Daedracian** [comment]
i got this when trying to in install the mining mod but it did this instead this is the 3rd i gotten an error first time new and old were clashing. ok chock that up to incompatibility due to being a year old, next i reinstall launcher everything seems good reinstall game launcher dosen't recognize what it downloaded trashcans it ok report it found a similar thread logged it under that done, now for some reason it works after sitting for hours awsome. mods, scroll to mining mod, select it, click install mod attemps and error message aaaahhahahahahhahahh i give i will take what i have a wait for it to be fixxed hopefully no more bugs atleast not major ones

**Comment by remyroy** [comment]
First, I would suggest using a more recent version of the launcher.

Your issue seems to be coming from the fact that the launcher seems to be unable to create a new directory in `C:\Users\jonny_000\Desktop\cdda\newmod`. Are you using something special that would prevent that like special permissions on your file system, encryption or other file system related application? Is that path even possible? Like can you create that directory yourself if you wanted to?

**Comment by Daedracian** [comment]
it was my computer locking the directory files away so the launcher could not access them
