### ISSUE TITLE
The preview pane is out of sync with the most recent build

### ISSUE THREAD

**Issue by Malkeus** [remyroy/CDDA-Game-Launcher#387]
I don't know what happened but the latest downloadable build is about 3 versions ahead of the preview pane. I saw there was some kind of Out of Memory glitch with the build server the other day, maybe that broke something.
https://i.imgur.com/2Te2Hkp.png

**Comment by remyroy** [comment]
We get our data from the CI server at http://gorgon.narc.ro:8080/job/Cataclysm-Matrix/ . The latest build there is 9641. That's the best information we can give for the changelog. @narc0tiq Do you know if there is an issue there?

**Comment by narc0tiq** [comment]
The build number is given by http://gorgon.narc.ro:8080/job/Cataclysm-Multijob/, which triggers the matrix as part of the build. I wouldn't recommend using it for change logging, though, because the multijob plugin seems to mess up the recent changes.

Maybe I should look into setting the build names in the matrix build.

**Comment by remyroy** [comment]
9646 just showed up in the launcher's changelog which should be fine now I think.

**Comment by remyroy** [comment]
I believe this is fixed now.
