### ISSUE TITLE
Often fails to update properly

### ISSUE THREAD

**Issue by Lazasar** [remyroy/CDDA-Game-Launcher#55]
About every 4th or 5th time I update, the update fails with a message. Sometimes its Windows Error 5 can't access save directory, or failed to delete save, or failed to do something to previous version directory. I wish I had a better and more deterministic understanding of the problem

**Comment by remyroy** [comment]
There are many possible causes for this. The update process needs to copy, move and delete files. If you have another process that is using those files, the launcher might not be able to complete the update. For instance, if you have the `previous_version` opened in a windows explorer window, it might block files.

I will need more information in order to start trying to solve your issue. Check out [How to Report Bugs Effectively](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
