### ISSUE TITLE
Error while updating. All saves lost.

### ISSUE THREAD

**Issue by petermorck** [remyroy/CDDA-Game-Launcher#68]
Running Windows 10. Launcher version 1.3.2. Running 64-bit tiles version of CDDA.
CDDA launcher exe is in the game root directory.
No checkboxes ticked in "Settings" tab of launcher.
No backups in launcher tab and no checkboxes ticked.
Had manually copied the world specific save folder to a backup, also inside the save folder, so I had like:
d:\games\cdda\save\myworld
d:\games\cdda\save\myworld-backup
I had an explorer window open in d:\games\cdda\save.

Just tried updating CDDA from 5300 to 5312.
I pressed Update Game in launcher and it downloaded game, then showed a small error text at the bottom. I don't remember it exactly, but it was something like
"The directory games//cdda//save// is not empty"
and my saves were wiped.
I mean the **entire save folder is empty**. All my saves are gone.

previous_version/save folder is also empty (could be because I had run the updater again to see if it would fail again, don't remember, but it didn't fail when I just tried again).

Does the launcher delete the entire save folder while updating? Why?

**Comment by remyroy** [comment]
The launcher goes to great lengths not to delete any file that could be important to you. When doing an update or installing the game, it will move all files from the selected directory into the previous_version directory inside your game directory (unless you selected one of the settings to prevent that which is not the default behavior), install the new game and copy back the preserved version various files like the save into the new version. It does not preserve multiple previous versions. If you update twice, it will remove the second to last version to make room for the new previous version.

The proper approach might have been to use the restore process instead of trying to update again after the error.

**Comment by petermorck** [comment]
Well I guess that part is my mistake. I was probably just trying to see if it would fail again if I repeated the operation. I've only known about the game (and the launcher) for 5-6 days and I'm not super familiar with it. Only after checking if I could reproduce the problem did I notice the previous_version directory.
Also, if I really wanted to make a proper backup, I should have put the copy in a completely different directory.

However the issue remains that the updater failed, and I'm not sure exactly why. I couldn't reproduce the error.
Perhaps throwing a popup when it fails would also be nice. The text in the bottom window is a little bit discrete for such an error.

Also, what does the "Use the launcher directory as the game directory" setting do? I can't find any documentation.

**Comment by remyroy** [comment]
That setting can be used to have the multiple launchers each in a game directory and each will use their own directory as the game directory instead of having a single global directory.
